"""Called 'migrate' with auto update script.'

Revision ID: 189ef51ce2fe
Revises: 14dda322c1b1
Create Date: 2019-04-27 17:19:54.703686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189ef51ce2fe'
down_revision = '14dda322c1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'attempted_login_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('attempted_login_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
