"""Called 'migrate' with auto update script.'

Revision ID: 3250b0f77c3f
Revises: 189ef51ce2fe
Create Date: 2019-04-27 17:20:08.260512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3250b0f77c3f'
down_revision = '189ef51ce2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('attempted_login_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'attempted_login_count')
    # ### end Alembic commands ###
