"""Called 'migrate' with auto update script.'

Revision ID: 32ab07a015bb
Revises: db8606a0bfc4
Create Date: 2019-04-27 17:43:20.536928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ab07a015bb'
down_revision = 'db8606a0bfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('attempted_login_count', sa.Integer()))
    op.execute("""
        UPDATE users
        SET attempted_login_count = 0
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'attempted_login_count')
    # ### end Alembic commands ###
