"""Called 'migrate' with auto update script.'

Revision ID: db8606a0bfc4
Revises: 3250b0f77c3f
Create Date: 2019-04-27 17:40:00.863724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8606a0bfc4'
down_revision = '3250b0f77c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'attempted_login_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('attempted_login_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
